### ISSUE TITLE
Why manual impls of traits `T` impls for `Value<T, D>`

### ISSUE THREAD

**Issue by Easyoakland** [thepowersgang/stack_dst-rs#13]
Why does [this](https://github.com/thepowersgang/stack_dst-rs/blob/master/src/value/trait_impls.rs) module exist?

Since Value impl `DerefMut<Target = T>` to the underlying `T` it can use the implementation on `T` instead of needing an implementation on itself. So why is there an implementation on `Value` that forwards to `T`?

This causes strange issues. For example, the below doesn't panic:

```rust
use stack_dst::{buffers::ConstArrayBuf, value::Value};

fn main() {
    assert_ne!(iter(true).size_hint(), (*iter(true)).size_hint());
    assert_ne!(iter(false).size_hint(), (*iter(false)).size_hint());
}
fn iter(with_args: bool) -> Value<dyn Iterator<Item = i32>, ConstArrayBuf<usize, 10>> {
    let iter = [1, 2, 3].into_iter();
    let args = std::env::args().filter_map(|x| x.parse().ok());

    let iter = if with_args {
        Value::new_stable(iter.chain(args), |v| v as _).expect("insufficient size")
    } else {
        Value::new_stable(iter, |v| v as _).expect("insufficient size")
    };
    iter
}

```

**Comment by thepowersgang** [comment]
The module exists to add trait impls for those traits - `Deref` doesn't work for trait impls, although it does work when doing method calls due to autoderef.

The `Iterator` impl needs to properly forward the `size_hint` function, that's a bug.

**Comment by Easyoakland** [comment]
When would one use the `Iterator` impl of `Value` instead of the [`&mut I`](https://doc.rust-lang.org/src/core/iter/traits/iterator.rs.html#4165) impl?

**Comment by thepowersgang** [comment]
Well, you could get a `&mut dyn Iterator` from `Value` if you wanted, but the idea of these impls is to avoid you needing to.
