### ISSUE TITLE
Reference / lifetime-bound DSTs

### ISSUE THREAD

**Issue by dhardy** [thepowersgang/stack_dst-rs#4]
Nice crate pushing the boundaries of what can be done with Rust!

As an extension, it would be nice to have a `RefA<'a>` type — something with a lifetime parameter. This might be possible by storing the data-pointer as `data: &'a ()` or similar (possibly with separate `&mut` version).

This still wouldn't solve [my problem](https://github.com/dhardy/kas/pull/57) (which involves storing a struct containing three lifetime-bound references), but I suspect there's not a way to do this in Rust without HKT or some such.

**Comment by thepowersgang** [comment]
Do you mean a version of `ValueA` that stores the data in a provided data buffer (instead of inline)? Or just being able to store DSTs that borrow? The latter should already be possible (there's no `'static` bound)

**Comment by dhardy** [comment]
The latter. It's possible with `unsafe` code, but there is currently no way of tying a lifetime to a `ValueA` object.

If you look at what I've use GATs for, references are [bound to an associated type with a given lifetime](https://github.com/dhardy/kas/pull/57/files#diff-4244198cf909c63fc5d4affad3c40126R91); compare with the non-GAT version above which must transmute the lifetimes. The equivalent version using stack_dst must use the `unsafe` transmuted version ([here wrapping the transmuting implementation](https://github.com/dhardy/kas/pull/57/files#diff-326cb0052191a34dfadf76f67de68cf3R89)).

**Comment by thepowersgang** [comment]
Just using `ValueA<dyn Foo + 'a, [usize; 2]>` should work

**Comment by dhardy** [comment]
Aha, that does what I need. Thanks!
