### ISSUE TITLE
Possible to pass wrongly typed vtable back in `new_stable`

### ISSUE THREAD

**Issue by Nemo157** [thepowersgang/stack_dst-rs#6]
```rust
use stack_dst::Value;

fn main() {
    let val1 = Value::new_stable((0, 0), |e| e as _).unwrap();
    let val2 = Value::new_stable((0, 0), |e| &e.0 as _).unwrap();
    dbg!(val1, val2);
}
```

In this `val2` is created with the vtable for `impl Debug for i32` instead of the vtable for `impl Debug for (i32, i32)` as stored in the value.

I believe this is as sound as the rest of `stack-dst` because there _is_ an `i32` at that memory location that can be accessed, but might be something to document somewhere.

A similar example is that you can return the vtable for `()` for any data:

```rust
use stack_dst::Value;

fn colocated_unit<T>(x: &T) -> &() {
    // Safety: Can materialize a unit at any non-zero memory location
    unsafe { (x as *const T).cast::<()>().as_ref().unwrap() }
}

fn main() {
    let val = Value::new_stable(0, |e| colocated_unit(e)).unwrap();
    dbg!(val);
}
```

Which is also likely sound since casting any `&T -> &Colocated<T>` with `#[repr(transparent)] struct Colocated<T>((), T);` would also be sound.

**Comment by danielhenrymantilla** [comment]
This can lead, for instance, to a memory leak:

```rust
fn forget (v: impl Sized)
{
    drop(Value::new_stable(v, colocated_unit).unwrap());
}
```

**Comment by thepowersgang** [comment]
Hmm... I'm not sure this can lead to full type confusion, as there is a defensive check that the first word of the returned pointer matches the pointer passed to the closure (which prevents any really hacky type confusion).

Worst case here is a memory leak, which is safe (... but maybe unexpected)

**Comment by danielhenrymantilla** [comment]
Since https://github.com/thepowersgang/stack_dst-rs/commit/acdbebb94cfb06e736f311cba4adf515c6ddb1a2 solves this issue, I think it can be closed 🙂
