### ISSUE TITLE
Const generics for databuf size

### ISSUE THREAD

**Issue by jkelleyrtp** [thepowersgang/stack_dst-rs#7]
Is it possible to provide a generic size parameter for Databuf instead of the 9 words it's currently locked at?

Would that lead to alignment issues?

I'd be willing to add it if it were possible. 

It would also be nice to have some trace logging installed to know when a stack allocation fails into a box allocation so we can increase the associated Databuf size.

**Comment by thepowersgang** [comment]
It is possible to change the size (using the `ValueA` structure).
Not sure about using const generics, as they'd require a major version bump (newer MSRV)

As for logging, you can easily add that by using `Value::new` directly (`new_or_boxed` is a very simple wrapper, see https://github.com/thepowersgang/stack_dst-rs/blob/master/src/value/mod.rs#L77)
